import type { ThemeDefinition } from '@/types'

export const THEMES: ThemeDefinition[] = [
  {
    id: 'free_basic',
    name: 'Basic',
    description: 'シンプルで清潔感のある白背景テーマ',
    price: 0,
    isFree: true,
    isAnimated: false,
    stripePriceId: null,
    previewColors: ['#ffffff', '#f3f4f6', '#111827'],
    series: 'free',
    prerequisiteId: null,
  },
  {
    id: 'free_dark',
    name: 'Simple Dark',
    description: 'スタイリッシュなダークテーマ',
    price: 0,
    isFree: true,
    isAnimated: false,
    stripePriceId: null,
    previewColors: ['#0a0a0a', '#1a1a1a', '#ffffff'],
    series: 'free',
    prerequisiteId: null,
  },
  {
    id: 'luxury_black',
    name: 'Luxury Black',
    description: 'ゴールドアクセントで高級感を演出',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_BLACK ?? null,
    previewColors: ['#0a0a0a', '#d4af37', '#1a1a1a'],
    series: 'luxury',
    prerequisiteId: null,
  },
  {
    id: 'luxury_navy',
    name: 'Luxury Navy',
    description: 'ディープネイビー×ゴールドの上質なテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_NAVY ?? null,
    previewColors: ['#0a0f1e', '#c8a96e', '#1a2540'],
    series: 'luxury',
    prerequisiteId: 'luxury_black',
  },
  {
    id: 'luxury_ivory',
    name: 'Luxury Ivory',
    description: 'アイボリー×アンティークゴールドの洗練されたテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_IVORY ?? null,
    previewColors: ['#f8f5ef', '#a07840', '#ede8de'],
    series: 'luxury',
    prerequisiteId: 'luxury_navy',
  },

  {
    id: 'neon_glow',
    name: 'Neon Glow',
    description: 'ピンク×シアンのサイバーネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_GLOW ?? null,
    previewColors: ['#0d0d0d', '#ff00ff', '#00ffff'],
    series: 'neon',
    prerequisiteId: null,
  },
  {
    id: 'neon_amber',
    name: 'Neon Amber',
    description: 'オレンジ×ゴールドの熱いネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_AMBER ?? null,
    previewColors: ['#0a0800', '#ff8c00', '#ffd700'],
    series: 'neon',
    prerequisiteId: 'neon_glow',
  },
  {
    id: 'neon_violet',
    name: 'Neon Violet',
    description: 'パープル×グリーンのサイバーパンクネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_VIOLET ?? null,
    previewColors: ['#050510', '#bf00ff', '#39ff14'],
    series: 'neon',
    prerequisiteId: 'neon_amber',
  },
]

export function getThemeById(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id)
}

export const FREE_THEME_IDS = THEMES.filter((t) => t.isFree).map((t) => t.id)
export const PAID_THEME_IDS = THEMES.filter((t) => !t.isFree).map((t) => t.id)
