import type { ThemeDefinition } from '@/types'

export const THEMES: ThemeDefinition[] = [
  {
    id: 'free_basic',
    name: 'Basic',
    description: 'シンプルで清潔感のある白背景テーマ',
    price: 0,
    isFree: true,
    isAnimated: false,
    stripePriceId: null,
    previewColors: ['#ffffff', '#f3f4f6', '#111827'],
    series: 'free',
    prerequisiteId: null,
  },
  {
    id: 'free_dark',
    name: 'Simple Dark',
    description: 'スタイリッシュなダークテーマ',
    price: 0,
    isFree: true,
    isAnimated: false,
    stripePriceId: null,
    previewColors: ['#0a0a0a', '#1a1a1a', '#ffffff'],
    series: 'free',
    prerequisiteId: null,
  },
  {
    id: 'luxury_ivory',
    name: 'Luxury Ivory',
    description: 'アイボリー×アンティークゴールドの洗練されたテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_IVORY ?? null,
    previewColors: ['#f8f5ef', '#a07840', '#ede8de'],
    series: 'luxury',
    prerequisiteId: null,
  },
  {
    id: 'luxury_black',
    name: 'Luxury Black',
    description: 'ゴールドアクセントで高級感を演出',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_BLACK ?? null,
    previewColors: ['#0a0a0a', '#d4af37', '#1a1a1a'],
    series: 'luxury',
    prerequisiteId: 'luxury_ivory',
  },
  {
    id: 'luxury_navy',
    name: 'Luxury Navy',
    description: 'ディープネイビー×ゴールドの上質なテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_LUXURY_NAVY ?? null,
    previewColors: ['#0a0f1e', '#c8a96e', '#1a2540'],
    series: 'luxury',
    prerequisiteId: 'luxury_black',
  },

  {
    id: 'neon_violet',
    name: 'Neon Violet',
    description: 'パープル×グリーンのサイバーパンクネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_VIOLET ?? null,
    previewColors: ['#050510', '#bf00ff', '#39ff14'],
    series: 'neon',
    prerequisiteId: null,
  },
  {
    id: 'neon_glow',
    name: 'Neon Glow',
    description: 'ピンク×シアンのサイバーネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_GLOW ?? null,
    previewColors: ['#0d0d0d', '#ff00ff', '#00ffff'],
    series: 'neon',
    prerequisiteId: 'neon_violet',
  },
  {
    id: 'neon_amber',
    name: 'Neon Amber',
    description: 'オレンジ×ゴールドの熱いネオンテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_NEON_AMBER ?? null,
    previewColors: ['#0a0800', '#ff8c00', '#ffd700'],
    series: 'neon',
    prerequisiteId: 'neon_glow',
  },

  // ── Sakura series ──
  {
    id: 'sakura_white',
    name: 'Sakura White',
    description: '薄桜×ダスティローズの和モダンなライトテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_SAKURA_WHITE ?? null,
    previewColors: ['#fdf6f8', '#c4849a', '#3d2030'],
    series: 'sakura',
    prerequisiteId: null,
  },
  {
    id: 'sakura_dusk',
    name: 'Sakura Dusk',
    description: '夜桜の深紅×チェリーピンクのダークテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_SAKURA_DUSK ?? null,
    previewColors: ['#13090d', '#e87ca8', '#8a2040'],
    series: 'sakura',
    prerequisiteId: 'sakura_white',
  },
  {
    id: 'sakura_matcha',
    name: 'Sakura Matcha',
    description: '抹茶の深緑×桜ピンクのコントラストテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_SAKURA_MATCHA ?? null,
    previewColors: ['#0a100a', '#7ab87a', '#e8a4b0'],
    series: 'sakura',
    prerequisiteId: 'sakura_dusk',
  },

  // ── Chrome series ──
  {
    id: 'chrome_silver',
    name: 'Chrome Silver',
    description: 'スティールブラック×シルバーの金属質感テーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_CHROME_SILVER ?? null,
    previewColors: ['#0e0f11', '#b8bec8', '#606872'],
    series: 'chrome',
    prerequisiteId: null,
  },
  {
    id: 'chrome_gold',
    name: 'Chrome Gold',
    description: 'ディープブラック×バーニッシュゴールドの金属光沢テーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_CHROME_GOLD ?? null,
    previewColors: ['#0c0a00', '#c8a830', '#e8d060'],
    series: 'chrome',
    prerequisiteId: 'chrome_silver',
  },
  {
    id: 'chrome_platinum',
    name: 'Chrome Platinum',
    description: 'ディープブラック×プラチナホワイトの純粋な金属感',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_CHROME_PLATINUM ?? null,
    previewColors: ['#08090c', '#dce4ec', '#8090a0'],
    series: 'chrome',
    prerequisiteId: 'chrome_gold',
  },
  {
    id: 'chrome_void',
    name: 'Chrome Void',
    description: '漆黒の宇宙×エレクトリックブルーのSFメタルテーマ',
    price: 500,
    isFree: false,
    isAnimated: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_CHROME_VOID ?? null,
    previewColors: ['#03040a', '#4090e0', '#80b8f0'],
    series: 'chrome',
    prerequisiteId: 'chrome_platinum',
  },
]

export function getThemeById(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id)
}

export const FREE_THEME_IDS = THEMES.filter((t) => t.isFree).map((t) => t.id)
export const PAID_THEME_IDS = THEMES.filter((t) => !t.isFree).map((t) => t.id)
